# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default_picture.png', upload_to=users.models.user_directory_path),
        ),
    ]
