# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='username',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='messaging',
            field=models.ManyToManyField(to='chat.Message'),
        ),
    ]
