# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messaging',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='companion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='companion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
