# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20181018_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_request', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_request', to=settings.AUTH_USER_MODEL)),
                ('to_request', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
