# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_requesttofriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
